"""
Seed script — populates exercises, workout templates, and achievements.

Usage:
    cd web/backend
    python scripts/seed_data.py

Idempotent: checks slug uniqueness before inserting.
"""

import sys
import os

# Make sure the backend root is on sys.path
_HERE = os.path.dirname(os.path.abspath(__file__))
_BACKEND_ROOT = os.path.dirname(_HERE)
if _BACKEND_ROOT not in sys.path:
    sys.path.insert(0, _BACKEND_ROOT)

from datetime import datetime, timezone
from app.core.database import SessionLocal
from app.models.exercise import Exercise
from app.models.workout import WorkoutTemplate, WorkoutTemplateExercise
from app.models.gamification import Achievement

NOW = lambda: datetime.now(timezone.utc)  # noqa: E731


# ─────────────────────────────────────────────────────────────────────────────
# EXERCISES  (55 total)
# ─────────────────────────────────────────────────────────────────────────────

EXERCISES = [
    # ── Strength — Chest ──────────────────────────────────────────────────────
    {
        "name": "Push-Up",
        "slug": "push-up",
        "description": "A classic bodyweight exercise targeting the chest, shoulders, and triceps.",
        "category": "strength",
        "difficulty": "beginner",
        "primary_muscles": ["chest", "triceps"],
        "secondary_muscles": ["shoulders", "core"],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Start in a high plank with hands shoulder-width apart.",
            "Lower your chest to just above the floor, keeping elbows at ~45°.",
            "Press back up to the starting position.",
            "Keep your core braced throughout the movement.",
        ],
        "tips": ["Don't let hips sag or pike up.", "Keep neck neutral."],
        "default_sets": 3, "default_reps": 12, "rest_seconds": 60,
        "calories_per_minute": 8.0,
        "accessibility_categories": ["low_impact"],
        "contraindications": ["wrist_injury", "shoulder_injury"],
        "supports_pose_analysis": True, "pose_model_key": "push_up",
    },
    {
        "name": "Incline Push-Up",
        "slug": "incline-push-up",
        "description": "An easier push-up variation with hands elevated on a bench or chair.",
        "category": "strength",
        "difficulty": "beginner",
        "primary_muscles": ["chest", "triceps"],
        "secondary_muscles": ["shoulders"],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Place hands on a sturdy elevated surface (bench, chair, wall).",
            "Perform a push-up while maintaining a straight body line.",
        ],
        "tips": ["Great for beginners or during shoulder recovery."],
        "default_sets": 3, "default_reps": 15, "rest_seconds": 60,
        "calories_per_minute": 6.0,
        "accessibility_categories": ["low_impact", "seated"],
        "contraindications": [],
        "supports_pose_analysis": False,
    },
    {
        "name": "Dumbbell Bench Press",
        "slug": "dumbbell-bench-press",
        "description": "A chest press using dumbbells, allowing a greater range of motion.",
        "category": "strength",
        "difficulty": "intermediate",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment_required": ["dumbbells", "bench"],
        "is_bodyweight": False,
        "instructions": [
            "Lie on a flat bench holding dumbbells at chest level.",
            "Press the dumbbells up until arms are fully extended.",
            "Lower slowly back to chest level.",
        ],
        "tips": ["Keep feet flat on the floor.", "Control the descent."],
        "default_sets": 3, "default_reps": 10, "rest_seconds": 90,
        "calories_per_minute": 7.0,
        "accessibility_categories": [],
        "contraindications": ["shoulder_injury"],
        "supports_pose_analysis": False,
    },
    # ── Strength — Back ───────────────────────────────────────────────────────
    {
        "name": "Bent-Over Dumbbell Row",
        "slug": "bent-over-dumbbell-row",
        "description": "Targets the upper and middle back with a unilateral dumbbell row.",
        "category": "strength",
        "difficulty": "intermediate",
        "primary_muscles": ["back"],
        "secondary_muscles": ["biceps", "core"],
        "equipment_required": ["dumbbells"],
        "is_bodyweight": False,
        "instructions": [
            "Hinge at the hips with a flat back.",
            "Pull the dumbbell toward your hip, keeping elbow close.",
            "Lower with control.",
        ],
        "tips": ["Brace core throughout.", "Avoid rounding the lower back."],
        "default_sets": 3, "default_reps": 10, "rest_seconds": 75,
        "calories_per_minute": 6.5,
        "accessibility_categories": [],
        "contraindications": ["lower_back_pain"],
        "supports_pose_analysis": False,
    },
    {
        "name": "Superman Hold",
        "slug": "superman-hold",
        "description": "Prone back extension that strengthens the lower back and glutes.",
        "category": "strength",
        "difficulty": "beginner",
        "primary_muscles": ["back", "glutes"],
        "secondary_muscles": [],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Lie face down with arms extended overhead.",
            "Simultaneously lift arms, chest, and legs off the floor.",
            "Hold for 2–3 seconds, then lower.",
        ],
        "tips": ["Keep neck neutral — don't crane upward."],
        "default_sets": 3, "default_reps": 12, "rest_seconds": 60,
        "calories_per_minute": 4.0,
        "accessibility_categories": ["low_impact"],
        "contraindications": ["lower_back_pain"],
        "supports_pose_analysis": False,
    },
    {
        "name": "Pull-Up",
        "slug": "pull-up",
        "description": "A challenging upper-body exercise using a pull-up bar.",
        "category": "strength",
        "difficulty": "advanced",
        "primary_muscles": ["back", "biceps"],
        "secondary_muscles": ["shoulders", "core"],
        "equipment_required": ["pull_up_bar"],
        "is_bodyweight": True,
        "instructions": [
            "Hang from bar with palms facing away, shoulder-width grip.",
            "Pull yourself up until chin clears the bar.",
            "Lower with control.",
        ],
        "tips": ["Engage lats before pulling.", "Avoid swinging."],
        "default_sets": 3, "default_reps": 6, "rest_seconds": 120,
        "calories_per_minute": 9.0,
        "accessibility_categories": [],
        "contraindications": ["shoulder_injury", "elbow_injury"],
        "supports_pose_analysis": False,
    },
    # ── Strength — Shoulders ──────────────────────────────────────────────────
    {
        "name": "Dumbbell Shoulder Press",
        "slug": "dumbbell-shoulder-press",
        "description": "Overhead press targeting the deltoids and triceps.",
        "category": "strength",
        "difficulty": "intermediate",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": ["triceps", "core"],
        "equipment_required": ["dumbbells"],
        "is_bodyweight": False,
        "instructions": [
            "Sit or stand holding dumbbells at shoulder height.",
            "Press overhead until arms are fully extended.",
            "Lower back to shoulder height.",
        ],
        "tips": ["Avoid locking out elbows at the top.", "Keep core tight."],
        "default_sets": 3, "default_reps": 10, "rest_seconds": 75,
        "calories_per_minute": 6.0,
        "accessibility_categories": ["standing"],
        "contraindications": ["shoulder_injury", "neck_injury"],
        "supports_pose_analysis": True, "pose_model_key": "shoulder_press",
    },
    {
        "name": "Lateral Raise",
        "slug": "lateral-raise",
        "description": "Isolation exercise for the lateral deltoids.",
        "category": "strength",
        "difficulty": "beginner",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": [],
        "equipment_required": ["dumbbells"],
        "is_bodyweight": False,
        "instructions": [
            "Stand holding dumbbells at sides.",
            "Raise arms to the sides until parallel to the floor.",
            "Lower with control.",
        ],
        "tips": ["Slightly bend elbows.", "Use lighter weights for good form."],
        "default_sets": 3, "default_reps": 15, "rest_seconds": 60,
        "calories_per_minute": 5.0,
        "accessibility_categories": ["standing"],
        "contraindications": ["shoulder_injury"],
        "supports_pose_analysis": False,
    },
    # ── Strength — Arms ───────────────────────────────────────────────────────
    {
        "name": "Dumbbell Bicep Curl",
        "slug": "dumbbell-bicep-curl",
        "description": "Classic isolation exercise for the biceps.",
        "category": "strength",
        "difficulty": "beginner",
        "primary_muscles": ["biceps"],
        "secondary_muscles": [],
        "equipment_required": ["dumbbells"],
        "is_bodyweight": False,
        "instructions": [
            "Stand holding dumbbells with palms facing forward.",
            "Curl weights toward shoulders, keeping elbows stationary.",
            "Lower slowly.",
        ],
        "tips": ["Don't swing — keep elbows pinned to your sides."],
        "default_sets": 3, "default_reps": 12, "rest_seconds": 60,
        "calories_per_minute": 4.5,
        "accessibility_categories": ["standing"],
        "contraindications": ["elbow_injury"],
        "supports_pose_analysis": True, "pose_model_key": "bicep_curl",
    },
    {
        "name": "Tricep Dip",
        "slug": "tricep-dip",
        "description": "Bodyweight tricep exercise using a chair or parallel bars.",
        "category": "strength",
        "difficulty": "beginner",
        "primary_muscles": ["triceps"],
        "secondary_muscles": ["chest", "shoulders"],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Place hands on the edge of a stable chair, fingers forward.",
            "Lower body by bending elbows to ~90°.",
            "Press back up to starting position.",
        ],
        "tips": ["Keep hips close to the chair.", "Elbows point straight back."],
        "default_sets": 3, "default_reps": 12, "rest_seconds": 60,
        "calories_per_minute": 6.0,
        "accessibility_categories": ["low_impact", "seated"],
        "contraindications": ["wrist_injury", "shoulder_injury"],
        "supports_pose_analysis": False,
    },
    {
        "name": "Hammer Curl",
        "slug": "hammer-curl",
        "description": "Bicep curl with a neutral grip, also targeting the brachialis.",
        "category": "strength",
        "difficulty": "beginner",
        "primary_muscles": ["biceps"],
        "secondary_muscles": [],
        "equipment_required": ["dumbbells"],
        "is_bodyweight": False,
        "instructions": [
            "Hold dumbbells with palms facing each other.",
            "Curl weights toward shoulders.",
            "Lower slowly.",
        ],
        "tips": ["Great for building arm thickness."],
        "default_sets": 3, "default_reps": 12, "rest_seconds": 60,
        "calories_per_minute": 4.5,
        "accessibility_categories": ["standing"],
        "contraindications": ["elbow_injury"],
        "supports_pose_analysis": False,
    },
    # ── Strength — Core ───────────────────────────────────────────────────────
    {
        "name": "Plank",
        "slug": "plank",
        "description": "Isometric core exercise that strengthens the entire midsection.",
        "category": "strength",
        "difficulty": "beginner",
        "primary_muscles": ["core"],
        "secondary_muscles": ["shoulders", "glutes"],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Get into a forearm plank position.",
            "Keep body in a straight line from head to heels.",
            "Hold for the target duration.",
        ],
        "tips": ["Don't let hips drop or rise.", "Breathe steadily."],
        "default_sets": 3, "default_duration_seconds": 30, "rest_seconds": 45,
        "calories_per_minute": 5.0,
        "accessibility_categories": ["low_impact"],
        "contraindications": ["wrist_injury", "lower_back_pain"],
        "supports_pose_analysis": False,
    },
    {
        "name": "Crunch",
        "slug": "crunch",
        "description": "A foundational core exercise targeting the upper abdominals.",
        "category": "strength",
        "difficulty": "beginner",
        "primary_muscles": ["core"],
        "secondary_muscles": [],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Lie on your back with knees bent, feet flat.",
            "Place hands behind head (light support, don't pull).",
            "Curl shoulders off the floor, pause, lower slowly.",
        ],
        "tips": ["Exhale on the way up.", "Focus on the contraction, not range."],
        "default_sets": 3, "default_reps": 20, "rest_seconds": 45,
        "calories_per_minute": 5.0,
        "accessibility_categories": ["low_impact"],
        "contraindications": ["neck_injury"],
        "supports_pose_analysis": False,
    },
    {
        "name": "Dead Bug",
        "slug": "dead-bug",
        "description": "Core stability exercise that minimises spinal stress.",
        "category": "strength",
        "difficulty": "beginner",
        "primary_muscles": ["core"],
        "secondary_muscles": [],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Lie on back, arms pointing to ceiling, hips and knees at 90°.",
            "Slowly extend opposite arm and leg toward the floor.",
            "Return and repeat on the other side.",
        ],
        "tips": ["Keep lower back pressed into the floor throughout."],
        "default_sets": 3, "default_reps": 10, "rest_seconds": 45,
        "calories_per_minute": 4.0,
        "accessibility_categories": ["low_impact"],
        "contraindications": [],
        "supports_pose_analysis": False,
    },
    {
        "name": "Russian Twist",
        "slug": "russian-twist",
        "description": "Rotational core exercise targeting the obliques.",
        "category": "strength",
        "difficulty": "intermediate",
        "primary_muscles": ["core"],
        "secondary_muscles": [],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Sit with knees bent, lean back slightly, feet off floor.",
            "Rotate torso side to side, touching the floor each time.",
            "Hold a weight for added resistance.",
        ],
        "tips": ["Keep chest tall.", "Rotate from torso, not just arms."],
        "default_sets": 3, "default_reps": 20, "rest_seconds": 45,
        "calories_per_minute": 6.0,
        "accessibility_categories": ["low_impact"],
        "contraindications": ["lower_back_pain"],
        "supports_pose_analysis": False,
    },
    # ── Strength — Legs ───────────────────────────────────────────────────────
    {
        "name": "Squat",
        "slug": "squat",
        "description": "The foundational lower-body compound exercise.",
        "category": "strength",
        "difficulty": "beginner",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings", "core"],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Stand with feet shoulder-width apart, toes slightly out.",
            "Push hips back and bend knees until thighs are parallel to the floor.",
            "Drive through heels to return to standing.",
        ],
        "tips": ["Keep chest up.", "Knees track over toes."],
        "default_sets": 3, "default_reps": 15, "rest_seconds": 60,
        "calories_per_minute": 8.0,
        "accessibility_categories": ["low_impact", "standing"],
        "contraindications": ["knee_injury"],
        "supports_pose_analysis": True, "pose_model_key": "squat",
    },
    {
        "name": "Goblet Squat",
        "slug": "goblet-squat",
        "description": "Squat variation holding a dumbbell or kettlebell at chest.",
        "category": "strength",
        "difficulty": "beginner",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["core"],
        "equipment_required": ["dumbbells"],
        "is_bodyweight": False,
        "instructions": [
            "Hold a dumbbell vertically at chest height.",
            "Squat down, keeping elbows inside knees.",
            "Drive back up.",
        ],
        "tips": ["Great for learning squat mechanics."],
        "default_sets": 3, "default_reps": 12, "rest_seconds": 75,
        "calories_per_minute": 8.0,
        "accessibility_categories": ["standing"],
        "contraindications": ["knee_injury"],
        "supports_pose_analysis": False,
    },
    {
        "name": "Lunge",
        "slug": "lunge",
        "description": "Unilateral lower-body exercise targeting quads and glutes.",
        "category": "strength",
        "difficulty": "beginner",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings", "calves"],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Stand with feet together.",
            "Step forward with one foot and lower until both knees are at ~90°.",
            "Push back to starting position and repeat on the other side.",
        ],
        "tips": ["Keep front knee above ankle.", "Upright torso."],
        "default_sets": 3, "default_reps": 12, "rest_seconds": 60,
        "calories_per_minute": 7.0,
        "accessibility_categories": ["standing"],
        "contraindications": ["knee_injury"],
        "supports_pose_analysis": True, "pose_model_key": "lunge",
    },
    {
        "name": "Reverse Lunge",
        "slug": "reverse-lunge",
        "description": "A lunge stepping backward — easier on the knees than forward lunge.",
        "category": "strength",
        "difficulty": "beginner",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings"],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Step backward and lower until both knees are at ~90°.",
            "Return to standing.",
        ],
        "tips": ["Better option for those with knee sensitivity."],
        "default_sets": 3, "default_reps": 12, "rest_seconds": 60,
        "calories_per_minute": 7.0,
        "accessibility_categories": ["standing", "low_impact"],
        "contraindications": [],
        "supports_pose_analysis": False,
    },
    {
        "name": "Glute Bridge",
        "slug": "glute-bridge",
        "description": "Floor-based glute exercise with no knee stress.",
        "category": "strength",
        "difficulty": "beginner",
        "primary_muscles": ["glutes"],
        "secondary_muscles": ["hamstrings", "core"],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Lie on back with knees bent, feet flat on floor.",
            "Drive hips up by squeezing glutes until body forms a straight line from shoulders to knees.",
            "Hold briefly, then lower.",
        ],
        "tips": ["Great for anyone with lower back issues.", "Don't hyperextend the lumbar."],
        "default_sets": 3, "default_reps": 15, "rest_seconds": 45,
        "calories_per_minute": 5.0,
        "accessibility_categories": ["low_impact"],
        "contraindications": [],
        "supports_pose_analysis": False,
    },
    {
        "name": "Calf Raise",
        "slug": "calf-raise",
        "description": "Isolation exercise for the gastrocnemius and soleus muscles.",
        "category": "strength",
        "difficulty": "beginner",
        "primary_muscles": ["calves"],
        "secondary_muscles": [],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Stand with feet hip-width apart.",
            "Rise on toes as high as possible.",
            "Lower slowly.",
        ],
        "tips": ["Use a step for greater range of motion."],
        "default_sets": 3, "default_reps": 20, "rest_seconds": 45,
        "calories_per_minute": 4.0,
        "accessibility_categories": ["standing"],
        "contraindications": [],
        "supports_pose_analysis": False,
    },
    {
        "name": "Romanian Deadlift",
        "slug": "romanian-deadlift",
        "description": "Hip-hinge movement targeting hamstrings and glutes.",
        "category": "strength",
        "difficulty": "intermediate",
        "primary_muscles": ["hamstrings", "glutes"],
        "secondary_muscles": ["back", "core"],
        "equipment_required": ["dumbbells"],
        "is_bodyweight": False,
        "instructions": [
            "Stand holding dumbbells in front of thighs.",
            "Hinge at hips, lowering weights along legs until feeling hamstring stretch.",
            "Squeeze glutes to return to standing.",
        ],
        "tips": ["Maintain a neutral spine throughout.", "Keep weights close to body."],
        "default_sets": 3, "default_reps": 10, "rest_seconds": 90,
        "calories_per_minute": 7.0,
        "accessibility_categories": [],
        "contraindications": ["lower_back_pain"],
        "supports_pose_analysis": False,
    },
    # ── Cardio ────────────────────────────────────────────────────────────────
    {
        "name": "Jumping Jacks",
        "slug": "jumping-jacks",
        "description": "Classic full-body cardiovascular exercise.",
        "category": "cardio",
        "difficulty": "beginner",
        "primary_muscles": ["full_body"],
        "secondary_muscles": [],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Start with feet together and arms at sides.",
            "Jump feet out wide while raising arms overhead.",
            "Return to starting position and repeat.",
        ],
        "tips": ["Land softly.", "Step instead of jump for low-impact modification."],
        "default_sets": 3, "default_duration_seconds": 30, "rest_seconds": 30,
        "calories_per_minute": 10.0,
        "accessibility_categories": ["high_impact"],
        "contraindications": ["knee_injury", "hip_injury"],
        "supports_pose_analysis": False,
    },
    {
        "name": "High Knees",
        "slug": "high-knees",
        "description": "Running in place with exaggerated knee lift.",
        "category": "cardio",
        "difficulty": "beginner",
        "primary_muscles": ["quads", "core"],
        "secondary_muscles": ["calves"],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Run in place, driving knees as high as possible.",
            "Pump arms in rhythm.",
        ],
        "tips": ["Keep torso upright.", "Step instead of run for low-impact."],
        "default_sets": 3, "default_duration_seconds": 30, "rest_seconds": 30,
        "calories_per_minute": 11.0,
        "accessibility_categories": ["high_impact"],
        "contraindications": ["knee_injury"],
        "supports_pose_analysis": False,
    },
    {
        "name": "Marching in Place",
        "slug": "marching-in-place",
        "description": "Low-impact cardio option suitable for all fitness levels.",
        "category": "cardio",
        "difficulty": "beginner",
        "primary_muscles": ["quads", "core"],
        "secondary_muscles": [],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Lift knees alternately to hip height while swinging opposite arm.",
        ],
        "tips": ["Ideal for beginners, seniors, or injury recovery."],
        "default_sets": 1, "default_duration_seconds": 120, "rest_seconds": 30,
        "calories_per_minute": 5.0,
        "accessibility_categories": ["low_impact", "standing"],
        "contraindications": [],
        "supports_pose_analysis": False,
    },
    {
        "name": "Burpee",
        "slug": "burpee",
        "description": "High-intensity full-body exercise combining a squat, plank, push-up, and jump.",
        "category": "hiit",
        "difficulty": "advanced",
        "primary_muscles": ["full_body"],
        "secondary_muscles": [],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "From standing, squat and place hands on floor.",
            "Jump or step feet back to plank.",
            "Do a push-up (optional).",
            "Jump or step feet forward, then jump up with arms overhead.",
        ],
        "tips": ["Scale down by removing the jump or push-up."],
        "default_sets": 3, "default_reps": 10, "rest_seconds": 90,
        "calories_per_minute": 14.0,
        "accessibility_categories": ["high_impact"],
        "contraindications": ["knee_injury", "lower_back_pain"],
        "supports_pose_analysis": False,
    },
    {
        "name": "Mountain Climbers",
        "slug": "mountain-climbers",
        "description": "Plank-based cardio exercise for core and cardiovascular fitness.",
        "category": "hiit",
        "difficulty": "intermediate",
        "primary_muscles": ["core"],
        "secondary_muscles": ["quads", "shoulders"],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Start in a high plank.",
            "Alternately drive knees toward chest in a running motion.",
        ],
        "tips": ["Keep hips level.", "Slow it down for core focus."],
        "default_sets": 3, "default_duration_seconds": 30, "rest_seconds": 45,
        "calories_per_minute": 12.0,
        "accessibility_categories": ["high_impact"],
        "contraindications": ["wrist_injury"],
        "supports_pose_analysis": False,
    },
    {
        "name": "Jump Rope",
        "slug": "jump-rope",
        "description": "Highly effective cardio exercise using a jump rope.",
        "category": "cardio",
        "difficulty": "beginner",
        "primary_muscles": ["calves", "core"],
        "secondary_muscles": [],
        "equipment_required": ["jump_rope"],
        "is_bodyweight": False,
        "instructions": [
            "Hold handles at hip height.",
            "Jump just high enough to clear the rope.",
        ],
        "tips": ["Land on the balls of your feet.", "Keep elbows close to body."],
        "default_sets": 3, "default_duration_seconds": 60, "rest_seconds": 60,
        "calories_per_minute": 12.0,
        "accessibility_categories": ["high_impact"],
        "contraindications": ["knee_injury", "ankle_injury"],
        "supports_pose_analysis": False,
    },
    # ── HIIT ──────────────────────────────────────────────────────────────────
    {
        "name": "Box Jump",
        "slug": "box-jump",
        "description": "Explosive plyometric exercise jumping onto a raised platform.",
        "category": "hiit",
        "difficulty": "intermediate",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["calves", "core"],
        "equipment_required": ["plyo_box"],
        "is_bodyweight": False,
        "instructions": [
            "Stand in front of a sturdy box.",
            "Jump explosively, landing softly on top of the box.",
            "Step down carefully.",
        ],
        "tips": ["Land with soft knees.", "Start with a lower box."],
        "default_sets": 3, "default_reps": 8, "rest_seconds": 90,
        "calories_per_minute": 13.0,
        "accessibility_categories": ["high_impact"],
        "contraindications": ["knee_injury", "ankle_injury"],
        "supports_pose_analysis": False,
    },
    {
        "name": "Squat Jump",
        "slug": "squat-jump",
        "description": "Explosive squat variation adding a jump at the top.",
        "category": "hiit",
        "difficulty": "intermediate",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["calves"],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Squat down to parallel.",
            "Explode upward into a jump.",
            "Land softly and immediately go into the next squat.",
        ],
        "tips": ["Land with bent knees to protect joints."],
        "default_sets": 3, "default_reps": 10, "rest_seconds": 75,
        "calories_per_minute": 12.0,
        "accessibility_categories": ["high_impact"],
        "contraindications": ["knee_injury"],
        "supports_pose_analysis": False,
    },
    # ── Flexibility & Yoga ────────────────────────────────────────────────────
    {
        "name": "Downward Dog",
        "slug": "downward-dog",
        "description": "Foundational yoga pose stretching the hamstrings, calves, and spine.",
        "category": "yoga",
        "difficulty": "beginner",
        "primary_muscles": ["hamstrings", "calves", "back"],
        "secondary_muscles": ["shoulders"],
        "equipment_required": ["yoga_mat"],
        "is_bodyweight": True,
        "instructions": [
            "Start on hands and knees.",
            "Lift hips up and back to form an inverted V.",
            "Press heels toward floor and chest toward thighs.",
        ],
        "tips": ["Bend knees slightly if hamstrings are tight."],
        "default_sets": 1, "default_duration_seconds": 30, "rest_seconds": 15,
        "calories_per_minute": 3.0,
        "accessibility_categories": ["low_impact"],
        "contraindications": ["wrist_injury"],
        "supports_pose_analysis": False,
    },
    {
        "name": "Child's Pose",
        "slug": "childs-pose",
        "description": "Restorative yoga pose for the lower back and hips.",
        "category": "yoga",
        "difficulty": "beginner",
        "primary_muscles": ["back"],
        "secondary_muscles": ["glutes"],
        "equipment_required": ["yoga_mat"],
        "is_bodyweight": True,
        "instructions": [
            "Kneel and sit back on heels.",
            "Extend arms forward on the floor, forehead down.",
            "Breathe deeply.",
        ],
        "tips": ["Widen knees for belly accommodation.", "Great cool-down stretch."],
        "default_sets": 1, "default_duration_seconds": 60, "rest_seconds": 0,
        "calories_per_minute": 1.5,
        "accessibility_categories": ["low_impact"],
        "contraindications": ["knee_injury"],
        "supports_pose_analysis": False,
    },
    {
        "name": "Hip Flexor Stretch",
        "slug": "hip-flexor-stretch",
        "description": "Kneeling lunge stretch targeting the hip flexors and quads.",
        "category": "flexibility",
        "difficulty": "beginner",
        "primary_muscles": ["quads"],
        "secondary_muscles": ["glutes"],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Kneel on one knee, opposite foot forward.",
            "Push hips forward gently until you feel a stretch in the front of the rear hip.",
            "Hold and breathe.",
        ],
        "tips": ["Don't arch the lower back."],
        "default_sets": 2, "default_duration_seconds": 30, "rest_seconds": 15,
        "calories_per_minute": 2.0,
        "accessibility_categories": ["low_impact"],
        "contraindications": ["knee_injury"],
        "supports_pose_analysis": False,
    },
    {
        "name": "Seated Hamstring Stretch",
        "slug": "seated-hamstring-stretch",
        "description": "Seated forward fold targeting the hamstrings.",
        "category": "flexibility",
        "difficulty": "beginner",
        "primary_muscles": ["hamstrings"],
        "secondary_muscles": ["back"],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Sit with legs extended.",
            "Reach forward toward toes, keeping back relatively straight.",
            "Hold the stretch.",
        ],
        "tips": ["Flex feet for deeper hamstring stretch."],
        "default_sets": 2, "default_duration_seconds": 30, "rest_seconds": 10,
        "calories_per_minute": 1.5,
        "accessibility_categories": ["low_impact", "seated"],
        "contraindications": [],
        "supports_pose_analysis": False,
    },
    {
        "name": "Pigeon Pose",
        "slug": "pigeon-pose",
        "description": "Deep hip opener targeting the piriformis and hip flexors.",
        "category": "yoga",
        "difficulty": "intermediate",
        "primary_muscles": ["glutes"],
        "secondary_muscles": ["quads"],
        "equipment_required": ["yoga_mat"],
        "is_bodyweight": True,
        "instructions": [
            "From downward dog, bring one knee forward to wrist.",
            "Extend back leg, keeping hips square.",
            "Lower torso forward for deeper stretch.",
        ],
        "tips": ["Use a block under the hip for tight hips."],
        "default_sets": 2, "default_duration_seconds": 45, "rest_seconds": 15,
        "calories_per_minute": 2.0,
        "accessibility_categories": ["low_impact"],
        "contraindications": ["knee_injury", "hip_injury"],
        "supports_pose_analysis": False,
    },
    # ── Balance ───────────────────────────────────────────────────────────────
    {
        "name": "Single-Leg Stand",
        "slug": "single-leg-stand",
        "description": "Simple balance exercise building ankle and core stability.",
        "category": "balance",
        "difficulty": "beginner",
        "primary_muscles": ["calves", "core"],
        "secondary_muscles": [],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Stand on one foot, slightly bending the standing knee.",
            "Hold balance for the target duration.",
            "Switch feet.",
        ],
        "tips": ["Focus on a fixed point to help balance.", "Use a wall for support initially."],
        "default_sets": 3, "default_duration_seconds": 30, "rest_seconds": 15,
        "calories_per_minute": 2.5,
        "accessibility_categories": ["standing", "low_impact"],
        "contraindications": ["ankle_injury"],
        "supports_pose_analysis": False,
    },
    {
        "name": "Tree Pose",
        "slug": "tree-pose",
        "description": "Yoga balance pose building lower body strength and focus.",
        "category": "balance",
        "difficulty": "beginner",
        "primary_muscles": ["core", "calves"],
        "secondary_muscles": ["glutes"],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Stand on one foot.",
            "Place the sole of the other foot on the inner thigh (or calf — never knee).",
            "Bring hands to heart centre or overhead.",
        ],
        "tips": ["Use a wall for support if needed."],
        "default_sets": 2, "default_duration_seconds": 30, "rest_seconds": 15,
        "calories_per_minute": 2.5,
        "accessibility_categories": ["standing", "low_impact"],
        "contraindications": ["ankle_injury"],
        "supports_pose_analysis": False,
    },
    # ── Rehabilitation / Accessible ───────────────────────────────────────────
    {
        "name": "Seated Leg Extension",
        "slug": "seated-leg-extension",
        "description": "Seated quad strengthening exercise requiring only a chair.",
        "category": "rehabilitation",
        "difficulty": "beginner",
        "primary_muscles": ["quads"],
        "secondary_muscles": [],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Sit upright in a sturdy chair.",
            "Extend one leg until straight, hold 2 seconds.",
            "Lower and repeat.",
        ],
        "tips": ["Suitable for beginners and those with mobility limitations."],
        "default_sets": 3, "default_reps": 15, "rest_seconds": 45,
        "calories_per_minute": 3.0,
        "accessibility_categories": ["seated", "low_impact"],
        "contraindications": ["knee_injury"],
        "supports_pose_analysis": False,
    },
    {
        "name": "Wall Push-Up",
        "slug": "wall-push-up",
        "description": "Standing push-up against a wall — the most accessible push-up variation.",
        "category": "strength",
        "difficulty": "beginner",
        "primary_muscles": ["chest", "triceps"],
        "secondary_muscles": ["shoulders"],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Stand facing a wall, hands at shoulder height.",
            "Lean in and bend elbows, then press back out.",
        ],
        "tips": ["Great for seniors, beginners, or post-surgery rehabilitation."],
        "default_sets": 3, "default_reps": 15, "rest_seconds": 45,
        "calories_per_minute": 4.0,
        "accessibility_categories": ["standing", "low_impact"],
        "contraindications": [],
        "supports_pose_analysis": False,
    },
    {
        "name": "Seated Shoulder Press",
        "slug": "seated-shoulder-press",
        "description": "Dumbbell shoulder press performed seated — good for those with balance concerns.",
        "category": "strength",
        "difficulty": "beginner",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": ["triceps"],
        "equipment_required": ["dumbbells"],
        "is_bodyweight": False,
        "instructions": [
            "Sit in a chair with back support, dumbbells at shoulder height.",
            "Press overhead, then lower.",
        ],
        "tips": ["Keep back against the chair."],
        "default_sets": 3, "default_reps": 12, "rest_seconds": 60,
        "calories_per_minute": 5.0,
        "accessibility_categories": ["seated", "low_impact"],
        "contraindications": ["shoulder_injury"],
        "supports_pose_analysis": False,
    },
    # ── Full Body ─────────────────────────────────────────────────────────────
    {
        "name": "Dumbbell Thruster",
        "slug": "dumbbell-thruster",
        "description": "A combined squat and shoulder press — excellent calorie burner.",
        "category": "hiit",
        "difficulty": "intermediate",
        "primary_muscles": ["quads", "shoulders"],
        "secondary_muscles": ["glutes", "triceps", "core"],
        "equipment_required": ["dumbbells"],
        "is_bodyweight": False,
        "instructions": [
            "Hold dumbbells at shoulder height.",
            "Squat to parallel, then drive up and press dumbbells overhead in one motion.",
            "Lower dumbbells as you descend into the next squat.",
        ],
        "tips": ["Use your leg drive to power the press.", "Keep core tight."],
        "default_sets": 3, "default_reps": 10, "rest_seconds": 90,
        "calories_per_minute": 11.0,
        "accessibility_categories": [],
        "contraindications": ["knee_injury", "shoulder_injury"],
        "supports_pose_analysis": False,
    },
    {
        "name": "Farmer's Carry",
        "slug": "farmers-carry",
        "description": "Loaded carry building grip strength, core stability, and overall conditioning.",
        "category": "strength",
        "difficulty": "beginner",
        "primary_muscles": ["core", "back"],
        "secondary_muscles": ["shoulders", "quads"],
        "equipment_required": ["dumbbells"],
        "is_bodyweight": False,
        "instructions": [
            "Hold a heavy dumbbell in each hand at your sides.",
            "Walk forward maintaining tall posture.",
        ],
        "tips": ["Keep shoulders packed down.", "Short, quick steps."],
        "default_sets": 3, "default_duration_seconds": 30, "rest_seconds": 60,
        "calories_per_minute": 7.0,
        "accessibility_categories": ["standing"],
        "contraindications": ["lower_back_pain"],
        "supports_pose_analysis": False,
    },
    {
        "name": "Step-Up",
        "slug": "step-up",
        "description": "Functional leg exercise using a step or box.",
        "category": "strength",
        "difficulty": "beginner",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings"],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "Stand facing a step or box.",
            "Step up with one foot, bringing the other foot up to meet it.",
            "Step back down and repeat on the other side.",
        ],
        "tips": ["Drive through the heel of the leading foot.", "Hold dumbbells for added resistance."],
        "default_sets": 3, "default_reps": 12, "rest_seconds": 60,
        "calories_per_minute": 7.0,
        "accessibility_categories": ["low_impact", "standing"],
        "contraindications": ["knee_injury"],
        "supports_pose_analysis": False,
    },
    {
        "name": "Bear Crawl",
        "slug": "bear-crawl",
        "description": "Full-body crawling movement building core and shoulder stability.",
        "category": "hiit",
        "difficulty": "intermediate",
        "primary_muscles": ["core", "shoulders"],
        "secondary_muscles": ["quads", "triceps"],
        "equipment_required": [],
        "is_bodyweight": True,
        "instructions": [
            "On all fours, knees hovering just off the floor.",
            "Move forward by stepping opposite hand and foot simultaneously.",
        ],
        "tips": ["Keep hips low — don't let them rise above your back."],
        "default_sets": 3, "default_duration_seconds": 30, "rest_seconds": 60,
        "calories_per_minute": 9.0,
        "accessibility_categories": [],
        "contraindications": ["wrist_injury", "knee_injury"],
        "supports_pose_analysis": False,
    },
]


# ─────────────────────────────────────────────────────────────────────────────
# ACHIEVEMENTS  (10 total)
# ─────────────────────────────────────────────────────────────────────────────

ACHIEVEMENTS = [
    {
        "name": "First Workout",
        "slug": "first_workout",
        "description": "Completed your first workout. Every journey starts with a single step!",
        "icon": "Dumbbell",
        "tier": "bronze",
        "points_value": 50,
        "criteria": {"type": "sessions_completed", "threshold": 1},
    },
    {
        "name": "Ten Workouts",
        "slug": "ten_workouts",
        "description": "Completed 10 workouts. You're building a solid habit!",
        "icon": "Award",
        "tier": "silver",
        "points_value": 200,
        "criteria": {"type": "sessions_completed", "threshold": 10},
    },
    {
        "name": "Fifty Workouts",
        "slug": "fifty_workouts",
        "description": "Completed 50 workouts. You're seriously dedicated!",
        "icon": "Trophy",
        "tier": "gold",
        "points_value": 1000,
        "criteria": {"type": "sessions_completed", "threshold": 50},
    },
    {
        "name": "Week Warrior",
        "slug": "week_streak",
        "description": "Maintained a 7-day workout streak.",
        "icon": "Flame",
        "tier": "silver",
        "points_value": 300,
        "criteria": {"type": "streak_days", "threshold": 7},
    },
    {
        "name": "Monthly Master",
        "slug": "month_streak",
        "description": "Maintained a 30-day workout streak. Incredible consistency!",
        "icon": "Crown",
        "tier": "gold",
        "points_value": 1500,
        "criteria": {"type": "streak_days", "threshold": 30},
    },
    {
        "name": "Level 5",
        "slug": "level_5",
        "description": "Reached level 5. You're getting stronger every day!",
        "icon": "Star",
        "tier": "bronze",
        "points_value": 250,
        "criteria": {"type": "level_reached", "threshold": 5},
    },
    {
        "name": "Level 10",
        "slug": "level_10",
        "description": "Reached level 10. Elite status achieved!",
        "icon": "Zap",
        "tier": "platinum",
        "points_value": 2000,
        "criteria": {"type": "level_reached", "threshold": 10},
    },
    {
        "name": "Pose Perfectionist",
        "slug": "pose_perfect",
        "description": "Scored 90+ on a pose analysis. Perfect form!",
        "icon": "Target",
        "tier": "silver",
        "points_value": 500,
        "criteria": {"type": "pose_score", "threshold": 90},
    },
    {
        "name": "Variety Pack",
        "slug": "variety_pack",
        "description": "Completed workouts in 5 different exercise categories.",
        "icon": "Grid",
        "tier": "bronze",
        "points_value": 150,
        "criteria": {"type": "categories_completed", "threshold": 5},
    },
    {
        "name": "Century Club",
        "slug": "hundred_workouts",
        "description": "Completed 100 workouts. You're a FitGenius legend!",
        "icon": "Medal",
        "tier": "platinum",
        "points_value": 5000,
        "criteria": {"type": "sessions_completed", "threshold": 100},
    },
]


# ─────────────────────────────────────────────────────────────────────────────
# WORKOUT TEMPLATES  (15 total)
# ─────────────────────────────────────────────────────────────────────────────

TEMPLATES = [
    {
        "name": "Beginner Full Body A",
        "description": "A gentle introduction to full-body resistance training.",
        "difficulty": "beginner",
        "category": "strength",
        "estimated_duration_minutes": 30,
        "fitness_goals": ["general", "muscle_gain"],
        "required_equipment": [],
        "accessibility_tags": ["low_impact"],
        "exercises": [
            ("squat", 3, 15, None),
            ("push-up", 3, 10, None),
            ("glute-bridge", 3, 15, None),
            ("plank", 3, None, 30),
            ("dead-bug", 2, 10, None),
        ],
    },
    {
        "name": "Beginner Full Body B",
        "description": "Second day of beginner full-body training with different movement patterns.",
        "difficulty": "beginner",
        "category": "strength",
        "estimated_duration_minutes": 30,
        "fitness_goals": ["general", "muscle_gain"],
        "required_equipment": [],
        "accessibility_tags": ["low_impact"],
        "exercises": [
            ("lunge", 3, 12, None),
            ("incline-push-up", 3, 12, None),
            ("crunch", 3, 20, None),
            ("superman-hold", 3, 12, None),
            ("calf-raise", 3, 20, None),
        ],
    },
    {
        "name": "Dumbbell Upper Body",
        "description": "Classic upper-body dumbbell workout for intermediate lifters.",
        "difficulty": "intermediate",
        "category": "strength",
        "estimated_duration_minutes": 40,
        "fitness_goals": ["muscle_gain"],
        "required_equipment": ["dumbbells"],
        "accessibility_tags": [],
        "exercises": [
            ("dumbbell-bench-press", 4, 10, None),
            ("bent-over-dumbbell-row", 4, 10, None),
            ("dumbbell-shoulder-press", 3, 10, None),
            ("dumbbell-bicep-curl", 3, 12, None),
            ("tricep-dip", 3, 12, None),
        ],
    },
    {
        "name": "Dumbbell Lower Body",
        "description": "Full lower-body dumbbell workout targeting quads, hamstrings, and glutes.",
        "difficulty": "intermediate",
        "category": "strength",
        "estimated_duration_minutes": 40,
        "fitness_goals": ["muscle_gain", "weight_loss"],
        "required_equipment": ["dumbbells"],
        "accessibility_tags": [],
        "exercises": [
            ("goblet-squat", 4, 12, None),
            ("romanian-deadlift", 4, 10, None),
            ("lunge", 3, 12, None),
            ("glute-bridge", 3, 15, None),
            ("calf-raise", 3, 20, None),
        ],
    },
    {
        "name": "Core Crusher",
        "description": "Targeted core workout focusing on stability and anti-rotation.",
        "difficulty": "beginner",
        "category": "strength",
        "estimated_duration_minutes": 20,
        "fitness_goals": ["general"],
        "required_equipment": [],
        "accessibility_tags": ["low_impact"],
        "exercises": [
            ("plank", 4, None, 40),
            ("dead-bug", 3, 10, None),
            ("crunch", 3, 20, None),
            ("russian-twist", 3, 20, None),
        ],
    },
    {
        "name": "Cardio Blast",
        "description": "High-energy cardio session to torch calories.",
        "difficulty": "intermediate",
        "category": "cardio",
        "estimated_duration_minutes": 25,
        "fitness_goals": ["weight_loss", "endurance"],
        "required_equipment": [],
        "accessibility_tags": [],
        "exercises": [
            ("jumping-jacks", 3, None, 45),
            ("high-knees", 3, None, 30),
            ("mountain-climbers", 3, None, 30),
            ("squat-jump", 3, 10, None),
            ("burpee", 3, 8, None),
        ],
    },
    {
        "name": "Low-Impact Cardio",
        "description": "Accessible cardio workout suitable for all fitness levels and mobility needs.",
        "difficulty": "beginner",
        "category": "cardio",
        "estimated_duration_minutes": 20,
        "fitness_goals": ["weight_loss", "endurance"],
        "required_equipment": [],
        "accessibility_tags": ["low_impact"],
        "exercises": [
            ("marching-in-place", 1, None, 120),
            ("step-up", 3, 12, None),
            ("glute-bridge", 3, 15, None),
            ("seated-leg-extension", 3, 15, None),
        ],
    },
    {
        "name": "HIIT Metcon",
        "description": "Advanced metabolic conditioning circuit.",
        "difficulty": "advanced",
        "category": "hiit",
        "estimated_duration_minutes": 35,
        "fitness_goals": ["weight_loss", "endurance"],
        "required_equipment": ["dumbbells"],
        "accessibility_tags": [],
        "exercises": [
            ("burpee", 4, 10, None),
            ("dumbbell-thruster", 4, 10, None),
            ("mountain-climbers", 4, None, 30),
            ("box-jump", 3, 8, None),
            ("bear-crawl", 3, None, 30),
        ],
    },
    {
        "name": "Push/Pull Superset",
        "description": "Alternating push and pull supersets for time-efficient training.",
        "difficulty": "intermediate",
        "category": "strength",
        "estimated_duration_minutes": 45,
        "fitness_goals": ["muscle_gain"],
        "required_equipment": ["dumbbells", "pull_up_bar"],
        "accessibility_tags": [],
        "exercises": [
            ("push-up", 4, 12, None),
            ("bent-over-dumbbell-row", 4, 10, None),
            ("dumbbell-shoulder-press", 3, 10, None),
            ("dumbbell-bicep-curl", 3, 12, None),
            ("tricep-dip", 3, 12, None),
        ],
    },
    {
        "name": "Yoga Flow",
        "description": "Gentle yoga-inspired mobility and flexibility session.",
        "difficulty": "beginner",
        "category": "flexibility",
        "estimated_duration_minutes": 30,
        "fitness_goals": ["flexibility", "general"],
        "required_equipment": ["yoga_mat"],
        "accessibility_tags": ["low_impact"],
        "exercises": [
            ("downward-dog", 3, None, 30),
            ("pigeon-pose", 2, None, 45),
            ("childs-pose", 2, None, 60),
            ("hip-flexor-stretch", 2, None, 30),
            ("seated-hamstring-stretch", 2, None, 30),
        ],
    },
    {
        "name": "Balance & Stability",
        "description": "Balance-focused workout for joint stability and proprioception.",
        "difficulty": "beginner",
        "category": "balance",
        "estimated_duration_minutes": 20,
        "fitness_goals": ["general"],
        "required_equipment": [],
        "accessibility_tags": ["low_impact", "standing"],
        "exercises": [
            ("single-leg-stand", 3, None, 30),
            ("tree-pose", 3, None, 30),
            ("glute-bridge", 3, 15, None),
            ("calf-raise", 3, 20, None),
        ],
    },
    {
        "name": "Shoulder & Arms",
        "description": "Dedicated shoulder and arm isolation workout.",
        "difficulty": "intermediate",
        "category": "strength",
        "estimated_duration_minutes": 35,
        "fitness_goals": ["muscle_gain"],
        "required_equipment": ["dumbbells"],
        "accessibility_tags": [],
        "exercises": [
            ("dumbbell-shoulder-press", 4, 10, None),
            ("lateral-raise", 4, 15, None),
            ("dumbbell-bicep-curl", 3, 12, None),
            ("hammer-curl", 3, 12, None),
            ("tricep-dip", 3, 12, None),
        ],
    },
    {
        "name": "Glutes & Hamstrings",
        "description": "Posterior chain focus for glutes and hamstrings.",
        "difficulty": "intermediate",
        "category": "strength",
        "estimated_duration_minutes": 35,
        "fitness_goals": ["muscle_gain", "weight_loss"],
        "required_equipment": ["dumbbells"],
        "accessibility_tags": ["low_impact"],
        "exercises": [
            ("glute-bridge", 4, 20, None),
            ("romanian-deadlift", 4, 10, None),
            ("reverse-lunge", 3, 12, None),
            ("step-up", 3, 12, None),
            ("superman-hold", 3, 12, None),
        ],
    },
    {
        "name": "Advanced Full Body",
        "description": "Challenging full-body workout combining strength and power.",
        "difficulty": "advanced",
        "category": "strength",
        "estimated_duration_minutes": 50,
        "fitness_goals": ["muscle_gain", "weight_loss"],
        "required_equipment": ["dumbbells", "pull_up_bar"],
        "accessibility_tags": [],
        "exercises": [
            ("pull-up", 4, 6, None),
            ("dumbbell-bench-press", 4, 10, None),
            ("romanian-deadlift", 4, 8, None),
            ("dumbbell-thruster", 3, 10, None),
            ("farmer's-carry", 3, None, 30),
        ],
    },
    {
        "name": "Chair-Based Workout",
        "description": "Full workout performed using a chair — accessible to all mobility levels.",
        "difficulty": "beginner",
        "category": "rehabilitation",
        "estimated_duration_minutes": 25,
        "fitness_goals": ["general"],
        "required_equipment": [],
        "accessibility_tags": ["seated", "low_impact"],
        "exercises": [
            ("seated-leg-extension", 3, 15, None),
            ("seated-shoulder-press", 3, 12, None),
            ("wall-push-up", 3, 15, None),
            ("tricep-dip", 3, 10, None),
            ("marching-in-place", 2, None, 60),
        ],
    },
]


# ─────────────────────────────────────────────────────────────────────────────
# RUNNER
# ─────────────────────────────────────────────────────────────────────────────

def seed():
    db = SessionLocal()
    try:
        print("Seeding exercises...")
        slug_to_id: dict[str, str] = {}

        for ex_data in EXERCISES:
            existing = db.query(Exercise).filter(Exercise.slug == ex_data["slug"]).first()
            if existing:
                slug_to_id[ex_data["slug"]] = existing.id
                continue

            ex = Exercise(
                **{k: v for k, v in ex_data.items() if k not in ("alternative_exercise_ids",)},
                alternative_exercise_ids=[],
                created_at=NOW(),
                updated_at=NOW(),
            )
            db.add(ex)
            db.flush()
            slug_to_id[ex_data["slug"]] = ex.id

        db.commit()
        print(f"  → {len(EXERCISES)} exercises processed")

        print("Seeding achievements...")
        for ach_data in ACHIEVEMENTS:
            existing = db.query(Achievement).filter(Achievement.slug == ach_data["slug"]).first()
            if existing:
                continue
            ach = Achievement(
                **ach_data,
                created_at=NOW(),
                updated_at=NOW(),
            )
            db.add(ach)

        db.commit()
        print(f"  → {len(ACHIEVEMENTS)} achievements processed")

        print("Seeding workout templates...")
        for tmpl_data in TEMPLATES:
            existing = db.query(WorkoutTemplate).filter(
                WorkoutTemplate.name == tmpl_data["name"]
            ).first()
            if existing:
                continue

            tmpl = WorkoutTemplate(
                name=tmpl_data["name"],
                description=tmpl_data["description"],
                difficulty=tmpl_data["difficulty"],
                category=tmpl_data["category"],
                estimated_duration_minutes=tmpl_data["estimated_duration_minutes"],
                fitness_goals=tmpl_data["fitness_goals"],
                required_equipment=tmpl_data["required_equipment"],
                accessibility_tags=tmpl_data["accessibility_tags"],
                created_at=NOW(),
                updated_at=NOW(),
            )
            db.add(tmpl)
            db.flush()

            for order_idx, (slug, sets, reps, duration) in enumerate(tmpl_data["exercises"]):
                exercise_id = slug_to_id.get(slug)
                if not exercise_id:
                    # Try a close match (e.g. farmers-carry slug variation)
                    exercise_id = slug_to_id.get(slug.rstrip("'s").replace("'s-", "s-"))
                if not exercise_id:
                    print(f"  WARNING: exercise slug '{slug}' not found — skipping")
                    continue

                te = WorkoutTemplateExercise(
                    template_id=tmpl.id,
                    exercise_id=exercise_id,
                    order_index=order_idx,
                    sets=sets,
                    reps=reps,
                    duration_seconds=duration,
                    rest_seconds=60,
                )
                db.add(te)

        db.commit()
        print(f"  → {len(TEMPLATES)} workout templates processed")
        print("\nSeed complete ✓")

    except Exception as exc:
        db.rollback()
        print(f"Seed failed: {exc}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed()
