import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Stitch Design System Colors
        surface: {
          DEFAULT: '#0f131c',
          50: '#f8f8fc',
          100: '#f1f1f8',
          600: '#262a33',
          700: '#181c24',
          800: '#1c2028',
          850: '#151922',
          900: '#0f131c',
          950: '#0a0e16',
        },
        'surface-dim': '#0f131c',
        'surface-bright': '#353942',
        'surface-container-lowest': '#0a0e16',
        'surface-container-low': '#181c24',
        'surface-container': '#1c2028',
        'surface-container-high': '#262a33',
        'surface-container-highest': '#31353e',
        'surface-variant': '#31353e',
        'on-surface': '#dfe2ee',
        'on-surface-variant': '#b9cacb',
        'inverse-surface': '#dfe2ee',
        'inverse-on-surface': '#2c3039',
        outline: '#849495',
        'outline-variant': '#3b494b',
        'surface-tint': '#00dbe9',

        primary: {
          DEFAULT: '#dbfcff',
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#00f0ff',
          600: '#00dbe9',
          700: '#006970',
          800: '#004f54',
          900: '#00363a',
          950: '#002022',
        },
        'on-primary': '#00363a',
        'primary-container': '#00f0ff',
        'on-primary-container': '#006970',
        'inverse-primary': '#006970',
        'primary-fixed': '#7df4ff',
        'primary-fixed-dim': '#00dbe9',
        'on-primary-fixed': '#002022',
        'on-primary-fixed-variant': '#004f54',

        secondary: {
          DEFAULT: '#4edea3',
          500: '#4edea3',
          600: '#00a572',
        },
        'on-secondary': '#003824',
        'secondary-container': '#00a572',
        'on-secondary-container': '#00311f',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',

        tertiary: {
          DEFAULT: '#faf3ff',
        },
        'on-tertiary': '#3c0091',
        'tertiary-container': '#e1d2ff',
        'on-tertiary-container': '#6d3bd7',
        'tertiary-fixed': '#e9ddff',
        'tertiary-fixed-dim': '#d0bcff',
        'on-tertiary-fixed': '#23005c',
        'on-tertiary-fixed-variant': '#5516be',

        error: {
          DEFAULT: '#ffb4ab',
        },
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',

        background: '#0f131c',
        'on-background': '#dfe2ee',

        accent: {
          400: '#4edea3',
          500: '#10b981',
          600: '#00a572',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Outfit', 'Cal Sans', 'Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'code-stat': ['Inter', 'monospace'],
        'stat-xl': ['Outfit', 'sans-serif'],
        'stat-xl-mobile': ['Outfit', 'sans-serif'],
        'headline-lg': ['Outfit', 'sans-serif'],
        'headline-md': ['Outfit', 'sans-serif'],
        'headline-sm': ['Outfit', 'sans-serif'],
        'display-lg': ['Outfit', 'sans-serif'],
        'display-lg-mobile': ['Outfit', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'stat-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'code-stat': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'stat-xl-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
      spacing: {
        gutter: '1rem',
        'gutter-desktop': '1.5rem',
        'gutter-mobile': '0.75rem',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-in-out',
        'slide-down': 'slideDown 0.3s ease-in-out',
        'pulse-subtle': 'pulseSubtle 2s infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        pulseSubtle: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
      },
    },
  },
  plugins: [],
}

export default config
